CREATE TABLE IF NOT EXISTS api_keys (id TEXT PRIMARY KEY, key_hash TEXT NOT NULL UNIQUE, created_at TEXT NOT NULL, active INTEGER NOT NULL DEFAULT 1);
CREATE TABLE IF NOT EXISTS usage_daily (key_id TEXT NOT NULL, day TEXT NOT NULL, requests INTEGER NOT NULL DEFAULT 0, PRIMARY KEY(key_id,day));
CREATE TABLE IF NOT EXISTS api_routes (slug TEXT PRIMARY KEY, title TEXT NOT NULL, description TEXT DEFAULT '', upstream_url TEXT NOT NULL, method TEXT NOT NULL DEFAULT 'GET', param_name TEXT NOT NULL DEFAULT 'q', enabled INTEGER NOT NULL DEFAULT 1, created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS metrics (id INTEGER PRIMARY KEY CHECK(id=1), total_requests INTEGER NOT NULL DEFAULT 0);
INSERT OR IGNORE INTO metrics(id,total_requests) VALUES(1,0);
