name = "saitamaapi"
main = "src/worker.js"
compatibility_date = "2026-10-01"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = "./public"
binding = "ASSETS"
run_worker_first = ["/api/*", "/dashboard/api/*"]

[[d1_databases]]
binding = "DB"
database_name = "1234"
database_id = "df174f31-09e6-4784-9fb9-63abbda1c110"
