const DAY = 86400;
const encoder = new TextEncoder();
const json = (data, status=200, headers={}) => new Response(JSON.stringify(data), {status, headers:{'content-type':'application/json; charset=utf-8','cache-control':'no-store',...headers}});
const html = (body,status=200) => new Response(body,{status,headers:{'content-type':'text/html; charset=utf-8','cache-control':'no-store','x-content-type-options':'nosniff','referrer-policy':'strict-origin-when-cross-origin'}});
const random = (n=32) => { const b=new Uint8Array(n); crypto.getRandomValues(b); return [...b].map(x=>x.toString(16).padStart(2,'0')).join(''); };
const hash = async s => [...new Uint8Array(await crypto.subtle.digest('SHA-256',encoder.encode(s)))].map(x=>x.toString(16).padStart(2,'0')).join('');
const b64url = bytes => btoa(String.fromCharCode(...new Uint8Array(bytes))).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'');
const parseCookies = req => Object.fromEntries((req.headers.get('cookie')||'').split(';').map(x=>x.trim()).filter(Boolean).map(x=>{const i=x.indexOf('=');return [x.slice(0,i),decodeURIComponent(x.slice(i+1))]}));
const cookie = (name,value,maxAge=60*60*24*7) => `${name}=${encodeURIComponent(value)}; Path=/; HttpOnly; Secure; SameSite=Lax; Max-Age=${maxAge}`;
const clearCookie = name => `${name}=; Path=/; HttpOnly; Secure; SameSite=Lax; Max-Age=0`;
const body = async req => {try{return await req.json()}catch{return {}}};
const safeUser = u => ({id:u.id,email:u.email,name:u.name,created_at:u.created_at});
async function sessionUser(req,env){const token=parseCookies(req).sai_session;if(!token)return null;const th=await hash(token);const row=await env.DB.prepare('SELECT u.id,u.email,u.name,u.created_at FROM sessions s JOIN users u ON u.id=s.user_id WHERE s.token_hash=? AND s.expires_at>?').bind(th,Math.floor(Date.now()/1000)).first();return row||null;}
async function makeSession(env,userId){const token=random(32), now=Math.floor(Date.now()/1000);await env.DB.prepare('INSERT INTO sessions(token_hash,user_id,expires_at,created_at) VALUES(?,?,?,?)').bind(await hash(token),userId,now+DAY*7,now).run();return token;}
async function pwHash(password,salt=random(16)){const key=await crypto.subtle.importKey('raw',encoder.encode(password),'PBKDF2',false,['deriveBits']);const bits=await crypto.subtle.deriveBits({name:'PBKDF2',salt:encoder.encode(salt),iterations:210000,hash:'SHA-256'},key,256);return `${salt}.${b64url(bits)}`;}
async function pwCheck(password,saved){if(!saved||!saved.includes('.'))return false;return (await pwHash(password,saved.split('.')[0]))===saved;}
function redirect(url,cookieHeader){return new Response(null,{status:302,headers:{location:url,...(cookieHeader?{'set-cookie':cookieHeader}:{})}})}
function origin(env){return env.APP_ORIGIN||'http://localhost:8787'}
async function auth(req,env,path){
 if(path==='/auth/register'&&req.method==='POST'){const b=await body(req),email=String(b.email||'').trim().toLowerCase(),name=String(b.name||'').trim().slice(0,80),password=String(b.password||'');if(!/^\S+@\S+\.\S+$/.test(email)||name.length<2||password.length<8)return json({error:'Ingresa nombre, correo válido y contraseña de al menos 8 caracteres.'},400);if(password.length>200)return json({error:'Contraseña demasiado larga.'},400);const existing=await env.DB.prepare('SELECT id FROM users WHERE email=?').bind(email).first();if(existing)return json({error:'Ese correo ya está registrado.'},409);const id=random(16),saved=await pwHash(password);await env.DB.prepare('INSERT INTO users(id,email,name,password_hash) VALUES(?,?,?,?)').bind(id,email,name,saved).run();const token=await makeSession(env,id);return json({ok:true,user:{id,email,name}},201,{'set-cookie':cookie('sai_session',token)});}
 if(path==='/auth/login'&&req.method==='POST'){const b=await body(req),email=String(b.email||'').trim().toLowerCase(),password=String(b.password||'');const u=await env.DB.prepare('SELECT * FROM users WHERE email=?').bind(email).first();if(!u||!await pwCheck(password,u.password_hash))return json({error:'Correo o contraseña incorrectos.'},401);const token=await makeSession(env,u.id);return json({ok:true,user:safeUser(u)},{headers:{}}.status||200,{'set-cookie':cookie('sai_session',token)});}
 if(path==='/auth/logout'&&req.method==='POST'){const token=parseCookies(req).sai_session;if(token)await env.DB.prepare('DELETE FROM sessions WHERE token_hash=?').bind(await hash(token)).run();return json({ok:true},200,{'set-cookie':clearCookie('sai_session')});}
 if(path==='/auth/me'){const u=await sessionUser(req,env);return u?json({user:u}):json({user:null},401);}
 if(path==='/auth/google'){if(!env.GOOGLE_CLIENT_ID||!env.GOOGLE_CLIENT_SECRET)return json({error:'Configura GOOGLE_CLIENT_ID y GOOGLE_CLIENT_SECRET en Cloudflare.'},503);const state=random(24),nonce=random(24);const u=new URL('https://accounts.google.com/o/oauth2/v2/auth');u.searchParams.set('client_id',env.GOOGLE_CLIENT_ID);u.searchParams.set('redirect_uri',`${origin(env)}/auth/google/callback`);u.searchParams.set('response_type','code');u.searchParams.set('scope','openid email profile');u.searchParams.set('state',state);u.searchParams.set('nonce',nonce);return redirect(u.toString(),cookie('sai_oauth_state',`${state}.${nonce}`,600));}
 if(path==='/auth/google/callback'){const c=parseCookies(req),u=new URL(req.url);if(!u.searchParams.get('code')||u.searchParams.get('state')!==c.sai_oauth_state?.split('.')[0])return redirect('/?auth_error=google_state',clearCookie('sai_oauth_state'));try{const tokenRes=await fetch('https://oauth2.googleapis.com/token',{method:'POST',headers:{'content-type':'application/x-www-form-urlencoded'},body:new URLSearchParams({code:u.searchParams.get('code'),client_id:env.GOOGLE_CLIENT_ID,client_secret:env.GOOGLE_CLIENT_SECRET,redirect_uri:`${origin(env)}/auth/google/callback`,grant_type:'authorization_code'})});const tokens=await tokenRes.json();if(!tokenRes.ok||!tokens.access_token)throw Error('token');const profileRes=await fetch('https://openidconnect.googleapis.com/v1/userinfo',{headers:{authorization:`Bearer ${tokens.access_token}`}});const p=await profileRes.json();if(!profileRes.ok||!p.email||!p.email_verified)throw Error('profile');let user=await env.DB.prepare('SELECT * FROM users WHERE google_sub=? OR email=?').bind(p.sub,p.email.toLowerCase()).first();if(user){if(!user.google_sub)await env.DB.prepare('UPDATE users SET google_sub=? WHERE id=?').bind(p.sub,user.id).run();}else{const id=random(16);await env.DB.prepare('INSERT INTO users(id,email,name,google_sub) VALUES(?,?,?,?)').bind(id,p.email.toLowerCase(),String(p.name||p.email).slice(0,80),p.sub).run();user={id};}const session=await makeSession(env,user.id);return redirect('/dashboard',cookie('sai_session',session));}catch{return redirect('/?auth_error=google_failed',clearCookie('sai_oauth_state'));}}
 return json({error:'Ruta de autenticación no encontrada.'},404);
}
async function api(req,env,path){const raw=req.headers.get('authorization')||'';const key=raw.startsWith('Bearer ')?raw.slice(7).trim():new URL(req.url).searchParams.get('apikey');if(!key)return json({error:'Falta API key. Usa Authorization: Bearer sai_...'},401);const keyHash=await hash(key);const row=await env.DB.prepare('SELECT k.id key_id,k.user_id FROM api_keys k WHERE k.key_hash=? AND k.revoked_at IS NULL').bind(keyHash).first();if(!row)return json({error:'API key inválida o revocada.'},401);const today=new Date().toISOString().slice(0,10),limit=Math.max(1,Number(env.DAILY_LIMIT)||295);const used=await env.DB.prepare('SELECT requests FROM usage_daily WHERE user_id=? AND day=?').bind(row.user_id,today).first();if((used?.requests||0)>=limit)return json({error:'Límite diario alcanzado.',limit,used:used.requests,remaining:0,reset:'00:00 UTC'},429,{'x-ratelimit-limit':String(limit),'x-ratelimit-remaining':'0'});let response;if(path==='/api/test')response=json({status:true,creator:'SaitamaAPI',message:'API key válida',timestamp:new Date().toISOString()});else if(path==='/api/ytsearch'){const q=new URL(req.url).searchParams.get('q')?.trim();if(!q)response=json({error:'Falta el parámetro q.'},400);else response=json({error:'Endpoint pendiente de conectar',endpoint:'/api/ytsearch',query:q,note:'Añade el proveedor de búsqueda en src/apis.js. La autenticación y cuota ya están preparadas.'},501);}else response=json({error:'Endpoint no encontrado',available:['/api/test','/api/ytsearch']},404);const status=response.status;await env.DB.prepare('INSERT INTO usage_daily(user_id,day,requests) VALUES(?,?,1) ON CONFLICT(user_id,day) DO UPDATE SET requests=requests+1').bind(row.user_id,today).run();await env.DB.prepare('INSERT INTO request_logs(user_id,endpoint,status) VALUES(?,?,?)').bind(row.user_id,path,status).run();const updated=await env.DB.prepare('SELECT requests FROM usage_daily WHERE user_id=? AND day=?').bind(row.user_id,today).first();const h=new Headers(response.headers);h.set('x-ratelimit-limit',String(limit));h.set('x-ratelimit-remaining',String(Math.max(0,limit-updated.requests)));return new Response(response.body,{status:response.status,headers:h});}
async function dashboard(req,env,path){const user=await sessionUser(req,env);if(!user)return redirect('/?login=required');if(path==='/api/dashboard/summary'){const today=new Date().toISOString().slice(0,10),limit=Math.max(1,Number(env.DAILY_LIMIT)||295);const usage=await env.DB.prepare('SELECT requests FROM usage_daily WHERE user_id=? AND day=?').bind(user.id,today).first();const keys=await env.DB.prepare('SELECT id,key_prefix,label,created_at FROM api_keys WHERE user_id=? AND revoked_at IS NULL ORDER BY created_at DESC').bind(user.id).all();const logs=await env.DB.prepare('SELECT endpoint,status,created_at FROM request_logs WHERE user_id=? ORDER BY id DESC LIMIT 8').bind(user.id).all();return json({user,limit,used:usage?.requests||0,remaining:Math.max(0,limit-(usage?.requests||0)),keys:keys.results||[],logs:logs.results||[]});}
 if(path==='/api/keys'&&req.method==='POST'){const count=await env.DB.prepare('SELECT COUNT(*) n FROM api_keys WHERE user_id=? AND revoked_at IS NULL').bind(user.id).first();if(count.n>=5)return json({error:'Máximo 5 claves activas por cuenta.'},400);const b=await body(req),plain='sai_'+random(24),id=random(12);await env.DB.prepare('INSERT INTO api_keys(id,user_id,key_hash,key_prefix,label) VALUES(?,?,?,?,?)').bind(id,user.id,await hash(plain),plain.slice(0,12)+'…',String(b.label||'Mi API key').slice(0,60)).run();return json({ok:true,key:plain,note:'Guarda esta clave ahora: no se vuelve a mostrar.'},201);}
 const match=path.match(/^\/api\/keys\/([a-f0-9]+)$/);if(match&&req.method==='DELETE'){const r=await env.DB.prepare("UPDATE api_keys SET revoked_at=datetime('now') WHERE id=? AND user_id=? AND revoked_at IS NULL").bind(match[1],user.id).run();return json({ok:(r.meta?.changes||0)>0});}
 if(path==='/dashboard')return html(await env.ASSETS.fetch(new URL('/dashboard.html',req.url)).then(r=>r.text()));return json({error:'No encontrado'},404);}
export default {async fetch(req,env){const url=new URL(req.url),path=url.pathname;try{if(path.startsWith('/auth/'))return await auth(req,env,path);if(path.startsWith('/api/')){if(path.startsWith('/api/dashboard/')||path==='/api/keys'||/^\/api\/keys\//.test(path))return await dashboard(req,env,path);return await api(req,env,path);}if(path==='/dashboard')return await dashboard(req,env,path);if(path==='/health')return json({ok:true,name:env.APP_NAME||'SaitamaAPI PRO'});return env.ASSETS.fetch(req);}catch(e){return json({error:'Error interno del servidor',detail:env.ENVIRONMENT==='development'?String(e):undefined},500);}}};
