const LIMIT=500, COOKIE='saitama_session', SESSION_SECONDS=604800;
const json=(d,s=200,h={})=>new Response(JSON.stringify(d),{status:s,headers:{'content-type':'application/json; charset=utf-8','cache-control':'no-store',...h}});
const enc=new TextEncoder();
function b64(bytes){let x='';for(const b of new Uint8Array(bytes))x+=String.fromCharCode(b);return btoa(x).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/g,'')}
function unb64(s){s=s.replace(/-/g,'+').replace(/_/g,'/');while(s.length%4)s+='=';return Uint8Array.from(atob(s),c=>c.charCodeAt(0))}
async function hash(s){return b64(await crypto.subtle.digest('SHA-256',enc.encode(s)))}
async function sign(secret,s){const k=await crypto.subtle.importKey('raw',enc.encode(secret),{name:'HMAC',hash:'SHA-256'},false,['sign']);return b64(await crypto.subtle.sign('HMAC',k,enc.encode(s)))}
async function newSession(env){const p=b64(enc.encode(JSON.stringify({user:'SaiDev145',exp:Math.floor(Date.now()/1000)+SESSION_SECONDS,nonce:crypto.randomUUID()})));return p+'.'+await sign(env.SESSION_SECRET,p)}
async function session(req,env){if(!env.SESSION_SECRET||!env.ADMIN_PASSWORD)return false;const c=req.headers.get('Cookie')||'',t=c.split(';').map(x=>x.trim()).find(x=>x.startsWith(COOKIE+'='))?.slice(COOKIE.length+1);if(!t)return false;const a=t.split('.');if(a.length!==2)return false;const expected=await sign(env.SESSION_SECRET,a[0]);if(expected!==a[1])return false;try{const p=JSON.parse(new TextDecoder().decode(unb64(a[0])));return p.user==='SaiDev145'&&p.exp>Date.now()/1000}catch{return false}}
const cookie=(v,age=SESSION_SECONDS)=>`${COOKIE}=${v}; Path=/; HttpOnly; Secure; SameSite=Strict; Max-Age=${age}`;
const day=()=>new Date().toISOString().slice(0,10);
const randKey=()=>{const b=crypto.getRandomValues(new Uint8Array(24));return 'sai_'+b64(b)};
async function stats(env){const [t,k,r,u]=await Promise.all([env.DB.prepare('SELECT total_requests FROM metrics WHERE id=1').first(),env.DB.prepare('SELECT COUNT(*) n FROM api_keys WHERE active=1').first(),env.DB.prepare('SELECT COUNT(*) n FROM api_routes WHERE enabled=1').first(),env.DB.prepare('SELECT COALESCE(SUM(requests),0) n FROM usage_daily WHERE day=?').bind(day()).first()]);return{ok:true,admin:'SaiDev145',totalRequests:t?.total_requests||0,activeKeys:k?.n||0,activeEndpoints:r?.n||0,requestsToday:u?.n||0,dailyLimit:LIMIT}}
async function routes(env){return (await env.DB.prepare('SELECT slug,title,description,upstream_url,method,param_name,enabled,created_at FROM api_routes ORDER BY created_at DESC').all()).results||[]}
async function dash(req,env,url){const p=url.pathname;
 if(p==='/dashboard/api/login'&&req.method==='POST'){if(!env.ADMIN_PASSWORD||!env.SESSION_SECRET)return json({ok:false,error:'Configura ADMIN_PASSWORD y SESSION_SECRET en Cloudflare.'},503);let b={};try{b=await req.json()}catch{};const a=enc.encode(String(b.password||'')),z=enc.encode(env.ADMIN_PASSWORD);let d=a.length^z.length;for(let i=0;i<Math.max(a.length,z.length);i++)d|=(a[i]||0)^(z[i]||0);if(d)return json({ok:false,error:'Contraseña incorrecta.'},401);return json({ok:true,admin:'SaiDev145'},200,{'set-cookie':cookie(await newSession(env))})}
 if(p==='/dashboard/api/logout'&&req.method==='POST')return json({ok:true},200,{'set-cookie':cookie('',0)});
 if(p==='/dashboard/api/me'&&req.method==='GET')return await session(req,env)?json({ok:true,admin:'SaiDev145'}):json({ok:false},401);
 if(!await session(req,env))return json({ok:false,error:'Sesión no autorizada. Inicia sesión.'},401);
 if(p==='/dashboard/api/stats'&&req.method==='GET')return json(await stats(env));
 if(p==='/dashboard/api/routes'&&req.method==='GET')return json({ok:true,routes:await routes(env)});
 if(p==='/dashboard/api/key/generate'&&req.method==='POST'){if(await env.DB.prepare('SELECT id FROM api_keys WHERE active=1 LIMIT 1').first())return json({ok:false,error:'Ya existe una clave activa. Elimínala primero.'},409);const key=randKey(),id=crypto.randomUUID();await env.DB.prepare('INSERT INTO api_keys(id,key_hash,created_at,active) VALUES(?,?,?,1)').bind(id,await hash(key),new Date().toISOString()).run();return json({ok:true,apiKey:key,message:'Guarda esta clave ahora; no se mostrará otra vez.'})}
 if(p==='/dashboard/api/key/delete'&&req.method==='POST'){await env.DB.prepare('UPDATE api_keys SET active=0 WHERE active=1').run();return json({ok:true,message:'API Key eliminada.'})}
 if(p==='/dashboard/api/routes'&&req.method==='POST'){let b={};try{b=await req.json()}catch{}const slug=String(b.slug||'').trim().toLowerCase(),title=String(b.title||'').trim(),up=String(b.upstream_url||'').trim(),method=String(b.method||'GET').toUpperCase(),param=String(b.param_name||'q').trim();if(!/^[a-z0-9_-]{2,50}$/.test(slug)||!title||!/^https:\/\/\S+$/i.test(up)||!['GET','POST'].includes(method)||!/^[a-zA-Z0-9_-]{1,40}$/.test(param))return json({ok:false,error:'Revisa slug, título, URL HTTPS, método y parámetro.'},400);try{await env.DB.prepare('INSERT INTO api_routes(slug,title,description,upstream_url,method,param_name,enabled,created_at) VALUES(?,?,?,?,?,?,1,?)').bind(slug,title,String(b.description||''),up,method,param,new Date().toISOString()).run()}catch{return json({ok:false,error:'El slug ya existe o no se pudo guardar.'},409)}return json({ok:true,message:'Endpoint agregado.'})}
 const m=p.match(/^\/dashboard\/api\/routes\/([a-z0-9_-]+)$/);if(m&&req.method==='DELETE'){await env.DB.prepare('DELETE FROM api_routes WHERE slug=?').bind(m[1]).run();return json({ok:true,message:'Endpoint eliminado.'})}return json({ok:false,error:'Ruta no encontrada.'},404)}
async function run(req,env,url){const slug=url.pathname.slice('/api/run/'.length).split('/')[0],key=req.headers.get('x-api-key')||url.searchParams.get('apikey')||'';if(!key.startsWith('sai_'))return json({ok:false,error:'Falta x-api-key.'},401);const row=await env.DB.prepare('SELECT id FROM api_keys WHERE key_hash=? AND active=1').bind(await hash(key)).first();if(!row)return json({ok:false,error:'API Key inválida o eliminada.'},401);const usedRow=await env.DB.prepare('SELECT requests FROM usage_daily WHERE key_id=? AND day=?').bind(row.id,day()).first(),used=usedRow?.requests||0;if(used>=LIMIT)return json({ok:false,error:'Límite diario de 500 solicitudes alcanzado.',used,limit:LIMIT},429);const r=await env.DB.prepare('SELECT slug,title,upstream_url,method,param_name FROM api_routes WHERE slug=? AND enabled=1').bind(slug).first();if(!r)return json({ok:false,error:'Endpoint no existe o está desactivado.'},404);await env.DB.prepare('INSERT INTO usage_daily(key_id,day,requests) VALUES(?,?,1) ON CONFLICT(key_id,day) DO UPDATE SET requests=requests+1').bind(row.id,day()).run();await env.DB.prepare('UPDATE metrics SET total_requests=total_requests+1 WHERE id=1').run();try{const target=new URL(r.upstream_url);for(const [k,v] of url.searchParams)if(k!=='apikey')target.searchParams.set(k,v);const init={method:r.method,headers:{accept:'application/json'}};if(r.method==='POST'){const b=await req.clone().json().catch(()=>({}));target.searchParams.set(r.param_name,String(b[r.param_name]||''));init.headers['content-type']='application/json';init.body=JSON.stringify(b)}const resp=await fetch(target,init);return new Response(resp.body,{status:resp.status,headers:{'content-type':resp.headers.get('content-type')||'application/json','cache-control':'no-store','x-saitama-limit':String(LIMIT),'x-saitama-used':String(used+1)}})}catch{return json({ok:false,error:'No se pudo conectar con la API externa.'},502)}}
export default{async fetch(req,env){const url=new URL(req.url);try{if(url.pathname.startsWith('/dashboard/api/'))return await dash(req,env,url);if(url.pathname.startsWith('/api/run/'))return await run(req,env,url);if(url.pathname==='/api/docs')return json({ok:true,name:'SaitamaAPI PRO',authentication:'Header x-api-key: sai_...',dailyLimit:LIMIT,endpoints:(await routes(env)).filter(r=>r.enabled).map(r=>({slug:r.slug,title:r.title,description:r.description,method:r.method,url:'/api/run/'+r.slug}))});if(url.pathname.startsWith('/api/'))return json({ok:false,error:'API route not found.'},404);return env.ASSETS?env.ASSETS.fetch(req):new Response('SaitamaAPI PRO')}catch{return json({ok:false,error:'Error interno del servidor.'},500)}}};
