const LIMIT=500;
const json=(d,s=200)=>new Response(JSON.stringify(d,null,2),{status:s,headers:{'content-type':'application/json; charset=utf-8','access-control-allow-origin':'*','access-control-allow-headers':'content-type,x-api-key,authorization,x-admin-token','access-control-allow-methods':'GET,POST,DELETE,OPTIONS'}});
const day=()=>new Date().toISOString().slice(0,10);
const rand=(n=16)=>{const b=new Uint8Array(n);crypto.getRandomValues(b);return [...b].map(x=>x.toString(16).padStart(2,'0')).join('')};
async function hash(s){const b=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(s));return [...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,'0')).join('')}
function keyOf(r){return r.headers.get('x-api-key')||(r.headers.get('authorization')||'').replace(/^Bearer\s+/i,'')}
async function auth(r,env){const k=keyOf(r);if(!k?.startsWith('sai_'))return{error:json({creator:'SAI',status:false,error:'API key requerida en x-api-key'},401)};const row=await env.DB.prepare('SELECT id FROM api_keys WHERE key_hash=? AND active=1').bind(await hash(k)).first();if(!row)return{error:json({creator:'SAI',status:false,error:'API key inválida o eliminada'},401)};const u=await env.DB.prepare('SELECT requests FROM usage_daily WHERE key_id=? AND day=?').bind(row.id,day()).first();if((u?.requests||0)>=LIMIT)return{error:json({creator:'SAI',status:false,error:'Límite diario alcanzado',limit:LIMIT,used:u.requests},429)};await env.DB.prepare('INSERT INTO usage_daily(key_id,day,requests) VALUES(?,?,1) ON CONFLICT(key_id,day) DO UPDATE SET requests=requests+1').bind(row.id,day()).run();await env.DB.prepare('UPDATE metrics SET total_requests=total_requests+1 WHERE id=1').run();return{row,key:k}}
export default {async fetch(req,env){const u=new URL(req.url),p=u.pathname;if(req.method==='OPTIONS')return new Response(null,{status:204,headers:{'access-control-allow-origin':'*','access-control-allow-headers':'content-type,x-api-key,authorization,x-admin-token','access-control-allow-methods':'GET,POST,DELETE,OPTIONS'}});if(!p.startsWith('/api/'))return env.ASSETS.fetch(req);try{
if(p==='/api/health')return json({creator:'SAI',status:true,name:'SaitamaAPI PRO',year:2026});
if(p==='/api/keys'&&req.method==='POST'){const k='sai_'+rand(),id=rand(12);await env.DB.prepare('INSERT INTO api_keys(id,key_hash,created_at) VALUES(?,?,?)').bind(id,await hash(k),new Date().toISOString()).run();return json({creator:'SAI',status:true,message:'Guarda esta clave; se muestra una sola vez.',apikey:k,limit:LIMIT,period:'daily'},201)}
if(p==='/api/keys/current'&&req.method==='GET'){const a=await auth(req,env);if(a.error)return a.error;const x=await env.DB.prepare('SELECT requests FROM usage_daily WHERE key_id=? AND day=?').bind(a.row.id,day()).first();return json({creator:'SAI',status:true,limit:LIMIT,used:x?.requests||0,remaining:Math.max(0,LIMIT-(x?.requests||0)),reset:'00:00 UTC'})}
if(p==='/api/keys/current'&&req.method==='DELETE'){const k=keyOf(req);if(!k)return json({creator:'SAI',status:false,error:'Falta API key'},401);await env.DB.prepare('UPDATE api_keys SET active=0 WHERE key_hash=?').bind(await hash(k)).run();return json({creator:'SAI',status:true,message:'API key eliminada'})}
if(p==='/api/stats'){const a=await auth(req,env);if(a.error)return a.error;const [us,tot,rs]=await Promise.all([env.DB.prepare('SELECT COUNT(*) n FROM api_keys WHERE active=1').first(),env.DB.prepare('SELECT total_requests FROM metrics WHERE id=1').first(),env.DB.prepare('SELECT COUNT(*) n FROM api_routes WHERE enabled=1').first()]);return json({creator:'SAI',status:true,year:2026,users:us.n,totalRequests:tot.total_requests,activeApis:rs.n,limitPerUserDaily:LIMIT})}
if(p==='/api/docs'){const {results=[]}=await env.DB.prepare('SELECT slug,title,description,method,param_name FROM api_routes WHERE enabled=1 ORDER BY title').all();return json({creator:'SAI',status:true,year:2026,apis:results.map(x=>({...x,endpoint:'/api/run/'+x.slug}))})}
if(p==='/api/admin/routes'&&req.method==='POST'){if(!env.ADMIN_TOKEN||req.headers.get('x-admin-token')!==env.ADMIN_TOKEN)return json({creator:'SAI',status:false,error:'Admin token inválido'},403);const b=await req.json(),slug=String(b.slug||'').toLowerCase().replace(/[^a-z0-9-]/g,''),title=String(b.title||'').slice(0,80),up=String(b.upstream_url||''),method=String(b.method||'GET').toUpperCase(),param=String(b.param_name||'q').replace(/[^a-zA-Z0-9_]/g,'');if(!slug||!title||!/^https:\/\/[^ ]+/.test(up)||!['GET','POST'].includes(method))return json({creator:'SAI',status:false,error:'Revisa slug, título, URL HTTPS y método'},400);await env.DB.prepare('INSERT INTO api_routes(slug,title,description,upstream_url,method,param_name,enabled,created_at) VALUES(?,?,?,?,?,?,1,?) ON CONFLICT(slug) DO UPDATE SET title=excluded.title,description=excluded.description,upstream_url=excluded.upstream_url,method=excluded.method,param_name=excluded.param_name,enabled=1').bind(slug,title,String(b.description||'').slice(0,250),up,method,param,new Date().toISOString()).run();return json({creator:'SAI',status:true,message:'API guardada y añadida a /api/docs',slug})}
if(p.startsWith('/api/run/')){const a=await auth(req,env);if(a.error)return a.error;const slug=p.slice(9),r=await env.DB.prepare('SELECT * FROM api_routes WHERE slug=? AND enabled=1').bind(slug).first();if(!r)return json({creator:'SAI',status:false,error:'Endpoint no encontrado'},404);const target=new URL(r.upstream_url);for(const [k,v] of u.searchParams)if(!['key','apikey'].includes(k))target.searchParams.set(k,v);const resp=await fetch(target.toString(),{headers:{accept:'application/json'}}),raw=await resp.text();let result;try{result=JSON.parse(raw)}catch{result={result:raw.slice(0,20000)}}return json({creator:'SAI',status:resp.ok,year:2026,endpoint:slug,result},resp.ok?200:502)}
return json({creator:'SAI',status:false,error:'Ruta no encontrada'},404)
}catch(e){return json({creator:'SAI',status:false,error:'Error interno del servidor'})}}};
